version: 1
from: "ghcr.io/nfra-project/kickstart-flavor-php:8.1"
ports: "80:80/tcp;25:25/tcp;143:143/tcp;465:465/tcp;993:993/tcp"

packages: [php8.1-curl, php8.1-http, php8.1-raphf, php8.1-zip]

config_file:
  template: "config.php.dist"
  target: "config.php"

command:
  build:
    - "echo \"www-data   ALL = (ALL) NOPASSWD: /bin/tar\" | sudo tee --append /etc/sudoers"
    - "composer update"
    - "sudo scripts/install-mail.sh"
    - "sudo phpdismod propro"

  init:
    - "sudo -E scripts/startup.sh"
  dev:

  run:
    - "sudo -E vendor/bin/cloudtool --autoload /opt/src/bootstrap.php --tpldir /opt/etc --target /etc"
    - "sudo -E scripts/restart-services.sh"

  config:
    - "sudo -E vendor/bin/cloudtool --autoload /opt/src/bootstrap.php --tpldir /opt/etc --target /etc --onchange /opt/scripts/restart-services.sh --watch"

  interval:
    - "sudo -E vendor/bin/cloudtool --autoload /opt/src/bootstrap.php --tpldir /opt/etc --target /etc"

  test:
    - "curl -f http://localhost"
