version: 1
from: "nfra/kickstart-flavor-php:7.4"

apache_document_root: /opt/www
apache_vhost_config: |
  FallbackResource /index.html
  php_admin_value file_uploads 0

config_file:
  template: "config.php.dist"
  target: "config.php"

command:
  build:
    - "echo \"www-data   ALL = (ALL) NOPASSWD: /bin/tar\" | sudo tee --append /etc/sudoers"
    - "composer update"
    - "sudo scripts/install-mail.sh"

  init:
    - "sudo -E scripts/startup.sh"
  dev:

  run:
    - "sudo -E vendor/bin/cloudtool --autoload /opt/src/bootstrap.php --tpldir /opt/etc --target /etc"
    - "sudo -E scripts/restart-services.sh"

  config:
    - "sudo -E vendor/bin/cloudtool --autoload /opt/src/bootstrap.php --tpldir /opt/etc --target /etc --onchange /opt/scripts/restart-services.sh --watch"

  interval:
    - "sudo -E vendor/bin/cloudtool --autoload /opt/src/bootstrap.php --tpldir /opt/etc --target /etc"

  test:
    - "curl -f http://localhost"
