name: build-latest-weekly


# Build once per week on Wednesdays 03:00
on:
  schedule:
      # * is a special character in YAML so you have to quote this string
      - cron:  '0 4 3 * *'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Test pull data
      run: docker pull infacamp/mailtainer:1.0
   # - name: Trigger testing run
     # run: "curl -X POST --data '{\"docker_tag\": \"1.0\"}' ${{ secrets.DAILY_DOCKERHUB_PULL_URL }}"
